Repository GSG-G13/ecommerce-team-6, pull requests merged in 2023-03, with the labels that each got.

#2 create-structure
  css/style.css
  customer.html
  index.html
  js/main.js
  seller.html
Labels: aprrove

#7 add git workshop heading & shadow styling
  css/Table.css
  seller.html
Labels: waiting

#8 Add Popup Form In Seller Page
  css/Table.css
  js/popup.js
  seller.html
Labels: aprrove

#9 create-customer page
  css/style.css
  customer.html
Labels: aprrove

#12 11-add-main-produts
  customer.html
  js/customer.js
  js/main.js
Labels: waiting

#14 Create Cart Page Style
  cart.html
  css/cart.css
Labels: waiting

#17 16-add-customer-js
  css/style.css
  customer.html
  js/customer.js
  js/main.js
Labels: waiting

#18 finish first version from landing page relate#4
  css/landing.css
  index.html
  js/landing.js
Labels: in progress

#20 add saller func
  js/main.js
  js/popup.js
  js/seller.js
  seller.html
Labels: aprrove

#22 final-edite-customer
  js/customer.js
  js/seller.js
Labels: waiting

#26 edit in cart page
  cart.html
  css/cart.css
  js/cart.js
  js/main.js
Labels: waiting

#31 Make Delete Cart Function Pure And Testing
  __tests__/TestingSeller.js
  __tests__/testCart.js
  js/cart.js
  js/helpers.js
  package-lock.json
Labels: waiting

#33 add serach feature and other edits
  css/Table.css
  css/cart.css
  css/style.css
  customer.html
  js/customer.js
  seller.html
Labels: waiting

#36 edit css link path
  seller.html
Labels: waiting

#39 Add Readme File To describe website
  README.md
Labels: waiting
